<?php
$title = 'Customer Order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php $user = $this->identity();
						if ($user && $user['user_type'] == 0) {?>
 <a href="<?php echo $this->url('application/default', array('controller'=>'customer','action' => 'index'));?>" class="btn btn-success">Customer Management</a>
 <hr>
<?php } ?>
<form name="search" id="search" action="<?=$this->url(Null, array('controller' => 'customer', 'action' => 'customerorder', 'id' => $id))?>">
<input type="text" id="from" name="from" value="<?php echo $from;?>"/>
<input type="text" id="to" name="to" value="<?php echo $to;?>"/>
<input type="submit" id="submit" name="sumit" value="Search"/>
</form>
 <table class="table table-striped table-bordered table-hover">
     <thead>
     <tr class="bg-info">        
         <th>Customer Name</th>
         <th>Total Cost</th>
         <th>Tax</th>
         <th>Total Order</th>
         <th>Order Date</th>
         <th colspan="3">Action</th>       
  
     </tr>
     </thead>
     <tbody>
    
          <?php 
		if(count($customers)>0):
		  foreach ($customers as $customer) : ?>
		 <tr>
            
             <td><?php echo $this->escapeHtml($customer->name); ?></td>
             <td><?php echo $this->escapeHtml($customer->total_cost); ?></td>
             <td><?php echo $this->escapeHtml($customer->tax); ?></td>
             <td><?php echo $this->escapeHtml($customer->order_total); ?></td>
             <td><?php echo $this->escapeHtml($customer->order_date); ?></td>
			 <td colspan="3">
			 
				<a href="<?php echo $this->url('application/default', array('action' => 'showorder','controller' => 'customer', 'id' => $customer->id));?>" class="btn btn-warning">Show order</a>
				
				<!---<a href="<?php echo $this->url('application/default', array('action' => 'edit','controller' => 'customer', 'id' => $customer->id));?>" class="btn btn-warning">Update</a>--->
				
				<a href="<?php echo $this->url('application/default', array('action' => 'orderdelete','controller' => 'customer', 'id' => $customer->id));?>" class="btn btn-warning">Delete</a>
				
             </td>
         </tr>
		<?php endforeach;
		else:?>
			 <tr>
				<td colspan="6" style="text-align:center;color:red;">No Records Found.</td>
			 </tr>
			
		<?php endif;?>
     </tbody>
 </table>
<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->customers,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'application/partial/paginator.phtml',
     // the route to link to when a user clicks a control link
	 array(
         'route' => 'listcustomerorder',
		 array('action'=>'customerorder',
		 'controller'=>'customer' ),
		 'data' =>$id,
     )
     
 );
 
 ?>
 	<script type="text/javascript">
		$(function () {
		$('#from').datepicker({
			format:'yyyy-mm-dd'});
			$('#to').datepicker({
			format:'yyyy-mm-dd'});
		});
	</script>