<?php
$title = 'Show Order Details';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php $user = $this->identity();
						if ($user && $user['user_type'] == 0) {?>
 <a href="<?php echo $this->url('application/default', array('controller'=>'customer','action' => 'customerorder'));?>" class="btn btn-success">Back to Order List</a>
						<?php }else{?>
						 <a href="<?php echo $this->url('application/default', array('controller'=>'customer','action' => 'customerorder', 'id'=>$user['id']));?>" class="btn btn-success">Back to Order List</a>
						<?php } ?>
 <hr>
 <table class="table table-striped table-bordered table-hover">
     <thead>
     <tr class="bg-info">        
         <th>Customer Name</th>
         <th>Product Name</th>
         <th>Qty</th>
         <th>Price Per Unit</th>
         <th>Total Amount</th>
         <th>Order Date</th>   
        
     </tr>
     </thead>
     <tbody>
    
          <?php 
		if (count($orders)>0): 
			 $sum = 0;
		  foreach($orders as $order):
		 
		  $sum +=$order->sale_price_per_unit*$order->qty;
		  ?>
		 <tr>
            
             <td><?php echo $this->escapeHtml($order->customerName); ?>1</td>
             <td><?php echo $this->escapeHtml($order->productName); ?></td>
             <td><?php echo $this->escapeHtml($order->qty); ?></td>
             <td><?php echo $this->escapeHtml($order->sale_price_per_unit); ?></td>
             <td><?php echo $this->escapeHtml($order->sale_price_per_unit*$order->qty); ?></td>
             <td><?php echo $this->escapeHtml($order->order_date); ?></td>
			
         </tr>
		  <?php endforeach; ?>
		<tr>
             <td colspan="5" align="right">Total Amount</td>
           
             <td ><?php echo $this->escapeHtml($sum); ?></td>
         </tr>
		<?php else: ?> 
			
			
			 <tr>
				<td colspan="6" style="text-align:center;color:red;">No1 Records Found.</td>
			 </tr>
			
		<?php endif;?>
     </tbody>
 </table>
<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->orders,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'application/partial/paginator.phtml',
     // the route to link to when a user clicks a control link
	 array(
         'route' => 'application/default',array('action'=>'index', 'controller'=>'customer')
     )
     
 );
 ?>