<?php
$title = 'Product Management';
$this->headTitle($title);
?>
<script>
$(document).ready(function() {
	var url = "/application/product/addcart"; 
	$("[id*='addcart_']").click(function(){
		var pidstr = $(this).attr('id').split('_');
		var pid = pidstr[1];	
		
		$.ajax({
			type: "POST",
			url: url,
			data: ({pid: pid}),		
			success: function(response){
				
					//console.log(response);
					if(response==1){
						window.location = "/application/product/createorder";
					}
					
				
			}
		});
	});
});
</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php //if(count($flashMessages)) : ?>
<!--<ul>
    <?php //foreach ($flashMessages as $msg) : ?>
    <li><?php //echo $msg; ?></li>
    <?php //endforeach; ?>
</ul>-->
<?php //endif; ?>
  <hr>
 
 <table class="table table-striped table-bordered table-hover">
     <thead>
     <tr class="bg-info">        
         <th>Product Name</th>
         <th>Unit of Measure</th>
         <th>Price</th>
         <th>Quantity</th>       
         <th>Actions</th>
     </tr>
     </thead>
     <tbody>
    
          <?php foreach ($products as $product) :  ?>
		  
		 <tr>
            
             <td><?php echo $this->escapeHtml($product->name); ?></td>
             <td><?php echo $this->escapeHtml($product->mname); ?></td>
             <td><?php echo $this->escapeHtml($product->price_per_unit); ?></td>
             <td><?php echo $this->escapeHtml($product->qty_in_stock); ?></td>
             
             <td>
			 <a href="JavaScript:void(0);" id="addcart_<?php echo $product->id;?>" class="btn btn-warning">Add to Cart</a>
			 
			 </td>            
         </tr>
		  <?php endforeach; ?>
     </tbody>

 </table>
 <?php
  echo $this->paginationControl(
		 // the paginator object
		 $this->products,
		 // the scrolling style
		 'sliding',
		 // the partial to use to render the control
		 'application/partial/paginator.phtml',
		 // the route to link to when a user clicks a control link
		array(
			 'route' => 'application/default',array('action'=>'index', 'controller'=>'product')
		 )
		 
	 );
	 ?>
