<?php if ($this->error): ?>
<p class="error">
There were one or more issues with your submission.
Please correct them as
indicated below.
</p>
<?php endif ?>

 <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add Product</div>
                <div class="panel-body">
								
					<?php
					$form = $this->form;
					$form->prepare();
					$form->setAttribute('action', $this->url(NULL, array('controller'=>'Product', 'action' => 'process')));
					$form->setAttribute('method', 'post');
					echo $this->form()->openTag($form);
					?>
					
					 <div class="form-group">
                         <?php 
						 echo $this->formLabel($form->get('name'));
						 echo $this->formElement($form->get('name'));
						echo $this->formElementErrors($form->get('name'));
						?>
                     </div>
					
					
					
					
					<div class="form-group">
						<?php 
						 echo $this->formLabel($form->get('id_uom'));
						 echo $this->formElement($form->get('id_uom'));
						echo $this->formElementErrors($form->get('id_uom'));
						?>
						
					</div>
					
					
					
					
					<div class="form-group">
						<?php 
						 echo $this->formLabel($form->get('price_per_unit'));
						 echo $this->formElement($form->get('price_per_unit'));
						echo $this->formElementErrors($form->get('price_per_unit'));
						?>	 
                           
                        </div>
						
						<div class="form-group">
						<?php 
						 echo $this->formLabel($form->get('qty_in_stock'));
						 echo $this->formElement($form->get('qty_in_stock'));
						echo $this->formElementErrors($form->get('qty_in_stock'));
						?>	 	 
                           
                        </div>		
					
					
					
					<div class="form-group">
						<?php
						echo $this->formElement($form->get('submit'));
						echo $this->formElementErrors($form->get('submit'));
						?>
					</div>
					<?php echo $this->form()->closeTag() ?>
				</div>
            </div>
        </div>
    </div>
</div>
