<?php
$title = 'Product Management';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php //if(count($flashMessages)) : ?>
<!--<ul>
    <?php //foreach ($flashMessages as $msg) : ?>
    <li><?php //echo $msg; ?></li>
    <?php //endforeach; ?>
</ul>-->
<?php //endif; ?>
 <a href="<?php echo $this->url('application/default', array('controller'=>'product','action' => 'create'));?>" class="btn btn-success">Create Product</a>
 <hr>
 <table class="table table-striped table-bordered table-hover">
     <thead>
     <tr class="bg-info">        
         <th>Product Name</th>
         <th>Unit of Measure</th>
         <th>Price</th>
         <th>Quantity</th>       
         <th colspan="2">Actions</th>
     </tr>
     </thead>
     <tbody>
    
          <?php foreach ($products as $product) : 		  ?>
		  
		 <tr>
            
             <td><?php echo $this->escapeHtml($product->name); ?></td>
             <td><?php echo $this->escapeHtml($product->mname); ?></td>
             <td><?php echo $this->escapeHtml($product->price_per_unit); ?></td>
             <td><?php echo $this->escapeHtml($product->qty_in_stock); ?></td>
             
             <td>
			 <a href="<?php echo $this->url('application/default', array('controller'=>'product','action' => 'create','id'=>$product->id));?>" class="btn btn-warning">Update</a>
			 
			 </td>
             <td>           
			<a href="<?php echo $this->url('application/default', array('action' => 'deleteproduct','controller' => 'product', 'id' => $product->id));?>" class="btn btn-info btn-danger js-submit-confirm">Delete</a>
             </td>
         </tr>
		  <?php endforeach; ?>
     </tbody>

 </table>
 <?php
  echo $this->paginationControl(
		 // the paginator object
		 $this->products,
		 // the scrolling style
		 'sliding',
		 // the partial to use to render the control
		 'application/partial/paginator.phtml',
		 // the route to link to when a user clicks a control link
		array(
			 'route' => 'listproduct',array('action'=>'index', 'controller'=>'product')
		 )
		 
	 );
	 ?>
 