<div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add User</div>
                <div class="panel-body">
				<?php
				$form = $this->form;
				$form->prepare();
				$form->setAttribute('action', $this->url(NULL,
				array('controller'=>'user', 'action' => 'add')));
				$form->setAttribute('method', 'post');
				$form->setAttribute('class', 'form-horizontal');
				$country_data=array('INDIA'=>'India','UK'=>'UK','USA'=>'USA','CHINA'=>'CHINA');
				
                echo $this->form()->openTag($form);
				  ?>
                        <div class="form-group">
							<?php echo $this->formLabel($form->get('name')); ?>
                            <div class="col-md-6">
							<?php 	echo $this->formElement($form->get('name')); 
									echo $this->formElementErrors($form->get('name'));
							?>
                            </div>
                        </div>

                        <div class="form-group">
                          <?php echo $this->formLabel($form->get('email')); ?>

                            <div class="col-md-6">
                                <?php 	echo $this->formElement($form->get('email')); 
									echo $this->formElementErrors($form->get('email'));
							?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('password')); ?>

                            <div class="col-md-6">
                                <?php 	
									echo $this->formElement($form->get('password')); 
									echo $this->formElementErrors($form->get('password'));
								?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('password_confirmation')); ?>

                            <div class="col-md-6">
                               <?php 	
									echo $this->formElement($form->get('password_confirmation')); 
									echo $this->formElementErrors($form->get('password_confirmation'));
								?>
                            </div>
                        </div>
						
						<div class="form-group">
                            <?php echo $this->formLabel($form->get('address1')); ?>

                            <div class="col-md-6">
                               <?php 	
									echo $this->formElement($form->get('address1')); 
									echo $this->formElementErrors($form->get('address1'));
								?>
                            </div>
                        </div>
						
						<div class="form-group">
                            <?php echo $this->formLabel($form->get('address2')); ?>

                            <div class="col-md-6">
                                <?php 	
									echo $this->formElement($form->get('address2')); 
									echo $this->formElementErrors($form->get('address2'));
								?>
                            </div>
                        </div>
						
						<div class="form-group">
                          <?php echo $this->formLabel($form->get('city')); ?>

                            <div class="col-md-6">
                                 <?php 	
									echo $this->formElement($form->get('city')); 
									echo $this->formElementErrors($form->get('city'));
								?>
                            </div>
                        </div>
						
						<div class="form-group">
                             <?php echo $this->formLabel($form->get('country')); ?>

                            <div class="col-md-6">
                              <?php 	
								echo $this->formElement($form->get('country')
								->setValueOptions($country_data)); 
									echo $this->formElementErrors($form->get('country'));
								?>
                            </div>
                        </div>
						
						

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-user"></i>Save User
                                </button>
                            </div>
                        </div>
					<?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>

