<?php
$title = 'User Management';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php //if(count($flashMessages)) : ?>
<!--<ul>
    <?php //foreach ($flashMessages as $msg) : ?>
    <li><?php //echo $msg; ?></li>
    <?php //endforeach; ?>
</ul>-->

<?php //endif; ?>

 <a href="<?php echo $this->url('application/default', array('controller'=>'user','action' => 'add'));?>" class="btn btn-success">Add User</a>
 <hr>
 <table class="table table-striped table-bordered table-hover">
     <thead>
     <tr class="bg-info">        
         <th>User Name</th>
         <th>Email</th>
         <th>City</th>
         <th align="center">Action</th>       
     </tr>
     </thead>
     <tbody>
    
          <?php 
		 
		if(count($customers)>0){
		  foreach ($customers as $customer){ ?>
		 <tr>
            
             <td><?php echo $this->escapeHtml($customer->name); ?></td>
             <td><?php echo $this->escapeHtml($customer->email); ?></td>
             <td><?php echo $this->escapeHtml($customer->city); ?></td>
             
			  <td align="center">

				<a href="<?php echo $this->url('application/default', array('action' => 'edit','controller' => 'user', 'id' => $customer->id));?>" class="btn btn-warning">Update</a>
			
				<a href="<?php echo $this->url('application/default', array('action' => 'deleteuser','controller' => 'user', 'id' => $customer->id));?>" class="btn btn-warning">Delete</a>
             </td>
         </tr>
		  <?php }?>
		<?php
		}else{?>
			 <tr>
				<td colspan="6" style="text-align:center;color:red;">No Records Found.</td>
			 </tr>
			
		<?php }?>
     </tbody>
 </table>
<?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->customers,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'application/partial/paginator.phtml',
     // the route to link to when a user clicks a control link
	 array(
         'route' => 'listuser', 'options' => array(
                  'action' => 'index','controller'=>'user'
                )
     )
     
 );
 ?>